# Generated by Django 4.1.5 on 2023-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_name',
            field=models.CharField(default='', max_length=255, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='status',
            name='style',
            field=models.TextField(default='', verbose_name='style'),
        ),
    ]
