# Generated by Django 4.1.5 on 2023-02-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shift_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteaddress',
            name='site_address_name',
            field=models.CharField(max_length=255, verbose_name='Site name'),
        ),
    ]
