# Generated by Django 4.1.5 on 2023-02-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_siteaddress_site_address_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Shiftuser',
        ),
    ]
