# Generated by Django 4.1.5 on 2023-02-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_rename_user_shiftuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_short',
            field=models.CharField(default='', max_length=12, verbose_name='Short name'),
        ),
    ]
