# Generated by Django 4.1.5 on 2023-02-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_shift_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.function'),
        ),
    ]
