# Generated by Django 4.1.5 on 2023-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_alter_shift_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_short',
            field=models.CharField(max_length=12, verbose_name='Short name'),
        ),
    ]
