# Generated by Django 4.1.5 on 2023-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_alter_customer_customer_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='function_short',
            field=models.CharField(default='', max_length=12, verbose_name='Function short'),
        ),
        migrations.AlterField(
            model_name='function',
            name='function_name',
            field=models.CharField(max_length=255, verbose_name='Function name'),
        ),
    ]
