# Generated by Django 4.1.5 on 2023-02-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_function_function_short_alter_function_function_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='style',
        ),
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.TextField(blank=True, max_length=100, verbose_name='style'),
        ),
        migrations.AddField(
            model_name='status',
            name='template_name',
            field=models.TextField(blank=True, default='', max_length=50, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=255, verbose_name='Status'),
        ),
    ]
