# Generated by Django 4.1.5 on 2023-02-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_remove_status_style_status_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='status',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Template'),
        ),
    ]
