# Generated by Django 4.1.5 on 2023-02-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0014_alter_status_color_alter_status_template_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ('start_date', 'start_time')},
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_date',
            field=models.DateField(default='start_date', verbose_name='End date'),
        ),
    ]
