# Generated by Django 4.1.5 on 2023-02-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_alter_shift_options_alter_shift_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
    ]
