# Generated by Django 4.1.5 on 2023-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0017_shiftuser_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
