# Generated by Django 4.1.5 on 2023-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0018_customer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='background color'),
        ),
    ]
